version: "3.7"

services:
    simulation-starter:
        build:
            context: .
            dockerfile: Dockerfile
        image: ghcr.io/evcommunities/simulation-starter:latest
        container_name: evcommunities_simulation_starter
        restart: "always"
        environment:
            HOST_FOLDER: ${HOST_FOLDER}
            SERVER_PORT: ${SERVER_PORT:-8500}
            SIMULATION_LOG_LEVEL: ${SIMULATION_LOG_LEVEL:-10}
            SIMULATION_LOG_FILE: ${SIMULATION_LOG_FILE:-simulation_starter.log}
            CONFIGURATION_FILE_PATH: ${CONFIGURATION_FILE_PATH:-configuration}
            PLATFORM_MANAGER_IMAGE: ${PLATFORM_MANAGER_IMAGE}
            SERVER_PRIVATE_TOKEN: ${SERVER_PRIVATE_TOKEN}
        ports:
            - ${SERVER_PORT:-8500}:${SERVER_PORT:-8500}
        volumes:
            - ./configuration:/app/configuration:ro
            - ./manifests:/app/manifests
            - ./simulations:/app/simulations
            - simulation_logs:/app/logs
            # NOTE: allowing access to host Docker socket can be a security risk
            - /var/run/docker.sock:/var/run/docker.sock:ro

volumes:
    simulation_logs:
        external: true
        name: simces_simulation_logs
